import Head from 'next/head'
import Navigation from './navigation'

export default function Layout({ title, children }) {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name={title} content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navigation />

            <main className='container px-4 mx-auto'>
                <div className='w-full md:max-w-xl mx-auto'>
                    {children}
                </div>
            </main>
        </div>
    )
}
